name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > aws-key.pem
          chmod 600 aws-key.pem

      - name: Deploy to EC2
        run: |
          ssh -i aws-key.pem -o StrictHostKeyChecking=no ubuntu@your-ec2-public-ip <<EOF
            cd /home/ubuntu/your-fastapi-repo
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
          EOF
